version: '1.0'
services:
  dns:
    build: ./bind
    container_name: dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./bind/data/:/etc/bind/:rw"
    networks:
      dmz:
        ipv4_address: 10.0.0.2
  nginx:
    build: ./nginx
    container_name: web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/var/www/html
      - ./nginx/conf:/etc/nginx
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      dmz:
        ipv4_address: 10.0.0.3
  mariadb:
    image: mariadb:latest
    container_name: db
    restart: always
    env_file: 
      - ./database/db.env
      - ./database/root.env
    volumes:
      - /home/samaze123/mysql:/var/lib/mysql
    networks:
      db_net:
        ipv4_address: 10.1.0.4
  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - "./nginx/html/site1:/var/www/html/site1"
    env_file:
      - ./database/db.env
    networks:
      dmz:
        ipv4_address: 10.0.0.5
      db_net:
        ipv4_address: 10.1.0.5

networks:
  dmz:
    name: dmz
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
  db_net:
    name: db_net
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1
